// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
  showtime_id,
  customer_id,
  order_id,
  payment_id,
  amount
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, showtime_id, customer_id, order_id, payment_id, amount, currency, status, created_at, updated_at
`

type CreateBookingParams struct {
	ShowtimeID int64       `json:"showtime_id"`
	CustomerID int64       `json:"customer_id"`
	OrderID    string      `json:"order_id"`
	PaymentID  pgtype.Text `json:"payment_id"`
	Amount     float64     `json:"amount"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ShowtimeID,
		arg.CustomerID,
		arg.OrderID,
		arg.PaymentID,
		arg.Amount,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ShowtimeID,
		&i.CustomerID,
		&i.OrderID,
		&i.PaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingById = `-- name: GetBookingById :one
SELECT id, showtime_id, customer_id, order_id, payment_id, amount, currency, status, created_at, updated_at FROM bookings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookingById(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingById, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ShowtimeID,
		&i.CustomerID,
		&i.OrderID,
		&i.PaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingsByShowtime = `-- name: GetBookingsByShowtime :many

SELECT id, showtime_id, customer_id, order_id, payment_id, amount, currency, status, created_at, updated_at FROM bookings
WHERE showtime_id = $1
ORDER BY updated_at DESC
`

// -- name: ListBookings :many
// SELECT * FROM bookings
// ORDER BY updated_at DESC
// LIMIT $1 OFFSET $2;
func (q *Queries) GetBookingsByShowtime(ctx context.Context, showtimeID int64) ([]Booking, error) {
	rows, err := q.db.Query(ctx, getBookingsByShowtime, showtimeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ShowtimeID,
			&i.CustomerID,
			&i.OrderID,
			&i.PaymentID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET payment_id= $2, status = $3
WHERE id = $1
RETURNING id, showtime_id, customer_id, order_id, payment_id, amount, currency, status, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID        int64       `json:"id"`
	PaymentID pgtype.Text `json:"payment_id"`
	Status    pgtype.Text `json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.PaymentID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ShowtimeID,
		&i.CustomerID,
		&i.OrderID,
		&i.PaymentID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
