// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: booked_seats.sql

package db

import (
	"context"
)

const createBookedSeat = `-- name: CreateBookedSeat :one
INSERT INTO booked_seats (
  booking_id,
  seat_id,
  show_time_id,
  price
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, booking_id, show_time_id, seat_id, price
`

type CreateBookedSeatParams struct {
	BookingID  int64   `json:"booking_id"`
	SeatID     int64   `json:"seat_id"`
	ShowTimeID int64   `json:"show_time_id"`
	Price      float64 `json:"price"`
}

func (q *Queries) CreateBookedSeat(ctx context.Context, arg CreateBookedSeatParams) (BookedSeat, error) {
	row := q.db.QueryRow(ctx, createBookedSeat,
		arg.BookingID,
		arg.SeatID,
		arg.ShowTimeID,
		arg.Price,
	)
	var i BookedSeat
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ShowTimeID,
		&i.SeatID,
		&i.Price,
	)
	return i, err
}

type CreateBookedSeatsBatchParams struct {
	BookingID  int64   `json:"booking_id"`
	SeatID     int64   `json:"seat_id"`
	ShowTimeID int64   `json:"show_time_id"`
	Price      float64 `json:"price"`
}

const getBookedSeat = `-- name: GetBookedSeat :one
SELECT id, booking_id, show_time_id, seat_id, price FROM booked_seats
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookedSeat(ctx context.Context, id int64) (BookedSeat, error) {
	row := q.db.QueryRow(ctx, getBookedSeat, id)
	var i BookedSeat
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ShowTimeID,
		&i.SeatID,
		&i.Price,
	)
	return i, err
}
