// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateBookedSeatsBatch implements pgx.CopyFromSource.
type iteratorForCreateBookedSeatsBatch struct {
	rows                 []CreateBookedSeatsBatchParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBookedSeatsBatch) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBookedSeatsBatch) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BookingID,
		r.rows[0].SeatID,
		r.rows[0].ShowTimeID,
		r.rows[0].Price,
	}, nil
}

func (r iteratorForCreateBookedSeatsBatch) Err() error {
	return nil
}

func (q *Queries) CreateBookedSeatsBatch(ctx context.Context, arg []CreateBookedSeatsBatchParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"booked_seats"}, []string{"booking_id", "seat_id", "show_time_id", "price"}, &iteratorForCreateBookedSeatsBatch{rows: arg})
}
