// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	IsGold    bool      `json:"is_gold"`
	Phone     string    `json:"phone"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Genre struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Movie struct {
	ID              int64     `json:"id"`
	Title           string    `json:"title"`
	GenreID         int32     `json:"genre_id"`
	NumberInStock   int32     `json:"number_in_stock"`
	DailyRentalRate float64   `json:"daily_rental_rate"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type Rental struct {
	ID           int64          `json:"id"`
	CustomerID   int32          `json:"customer_id"`
	MovieID      int32          `json:"movie_id"`
	DateOut      time.Time      `json:"date_out"`
	DateReturned sql.NullTime   `json:"date_returned"`
	RentalFee    sql.NullString `json:"rental_fee"`
}

type Seat struct {
	ID        int32     `json:"id"`
	TheaterID int32     `json:"theater_id"`
	Row       int32     `json:"row"`
	Col       int32     `json:"col"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Theater struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Rows      int32     `json:"rows"`
	Columns   int32     `json:"columns"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	FullName          string    `json:"full_name"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	IsAdmin           bool      `json:"is_admin"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}
