// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, description,poster,likes,trailer, runtime, language, release_date)
VALUES ($1, $2, $3, $4, $5, $6,$7,$8)
RETURNING id, title, description, poster, likes, trailer, runtime, language, release_date, created_at, updated_at
`

type CreateMovieParams struct {
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Poster      string      `json:"poster"`
	Likes       int32       `json:"likes"`
	Trailer     string      `json:"trailer"`
	Runtime     int64       `json:"runtime"`
	Language    string      `json:"language"`
	ReleaseDate pgtype.Date `json:"release_date"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie,
		arg.Title,
		arg.Description,
		arg.Poster,
		arg.Likes,
		arg.Trailer,
		arg.Runtime,
		arg.Language,
		arg.ReleaseDate,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Poster,
		&i.Likes,
		&i.Trailer,
		&i.Runtime,
		&i.Language,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, description, poster, likes, trailer, runtime, language, release_date, created_at, updated_at FROM movies WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Poster,
		&i.Likes,
		&i.Trailer,
		&i.Runtime,
		&i.Language,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, description, poster, likes, trailer, runtime, language, release_date, created_at, updated_at FROM movies ORDER BY id
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Poster,
			&i.Likes,
			&i.Trailer,
			&i.Runtime,
			&i.Language,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title=$2, description=$3,poster=$4,likes=$5,trailer=$6, runtime=$7, language=$8, release_date=$9, updated_at = now()
WHERE id = $1
RETURNING id, title, description, poster, likes, trailer, runtime, language, release_date, created_at, updated_at
`

type UpdateMovieParams struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Poster      string      `json:"poster"`
	Likes       int32       `json:"likes"`
	Trailer     string      `json:"trailer"`
	Runtime     int64       `json:"runtime"`
	Language    string      `json:"language"`
	ReleaseDate pgtype.Date `json:"release_date"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Poster,
		arg.Likes,
		arg.Trailer,
		arg.Runtime,
		arg.Language,
		arg.ReleaseDate,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Poster,
		&i.Likes,
		&i.Trailer,
		&i.Runtime,
		&i.Language,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
