// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: movies.sql

package db

import (
	"context"
	"time"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (title, description,poster,likes,trailer, duration_minutes, language, genre_id, release_date)
VALUES ($1, $2, $3, $4, $5, $6,$7,$8,$9)
RETURNING id, title, description, poster, likes, trailer, duration_minutes, language, genre_id, release_date, created_at, updated_at
`

type CreateMovieParams struct {
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	Poster          string    `json:"poster"`
	Likes           int32     `json:"likes"`
	Trailer         string    `json:"trailer"`
	DurationMinutes int32     `json:"duration_minutes"`
	Language        string    `json:"language"`
	GenreID         int32     `json:"genre_id"`
	ReleaseDate     time.Time `json:"release_date"`
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, createMovie,
		arg.Title,
		arg.Description,
		arg.Poster,
		arg.Likes,
		arg.Trailer,
		arg.DurationMinutes,
		arg.Language,
		arg.GenreID,
		arg.ReleaseDate,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Poster,
		&i.Likes,
		&i.Trailer,
		&i.DurationMinutes,
		&i.Language,
		&i.GenreID,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, description, poster, likes, trailer, duration_minutes, language, genre_id, release_date, created_at, updated_at FROM movies WHERE id = $1
`

func (q *Queries) GetMovie(ctx context.Context, id int64) (Movie, error) {
	row := q.db.QueryRowContext(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Poster,
		&i.Likes,
		&i.Trailer,
		&i.DurationMinutes,
		&i.Language,
		&i.GenreID,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, description, poster, likes, trailer, duration_minutes, language, genre_id, release_date, created_at, updated_at FROM movies ORDER BY id
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.QueryContext(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Movie{}
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Poster,
			&i.Likes,
			&i.Trailer,
			&i.DurationMinutes,
			&i.Language,
			&i.GenreID,
			&i.ReleaseDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :one
UPDATE movies
SET title=$2, description=$3,poster=$4,likes=$5,trailer=$6, duration_minutes=$7, language=$8, genre_id=$9, release_date=$10, updated_at = now()
WHERE id = $1
RETURNING id, title, description, poster, likes, trailer, duration_minutes, language, genre_id, release_date, created_at, updated_at
`

type UpdateMovieParams struct {
	ID              int64     `json:"id"`
	Title           string    `json:"title"`
	Description     string    `json:"description"`
	Poster          string    `json:"poster"`
	Likes           int32     `json:"likes"`
	Trailer         string    `json:"trailer"`
	DurationMinutes int32     `json:"duration_minutes"`
	Language        string    `json:"language"`
	GenreID         int32     `json:"genre_id"`
	ReleaseDate     time.Time `json:"release_date"`
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) (Movie, error) {
	row := q.db.QueryRowContext(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Poster,
		arg.Likes,
		arg.Trailer,
		arg.DurationMinutes,
		arg.Language,
		arg.GenreID,
		arg.ReleaseDate,
	)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Poster,
		&i.Likes,
		&i.Trailer,
		&i.DurationMinutes,
		&i.Language,
		&i.GenreID,
		&i.ReleaseDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
